name: Test ThermaSafeAI CI

on: [push, pull_request]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Print Python version
        run: python --version

      - name: Test CI pipeline
        run: echo "GitHub Actions CI is working ✅"
